stages:
  extract:
    cmd: python ./src/01_extraction.py
    deps:
    - data/genome/saccer3_sgd_2mu.fa
    - data/hic/loops_tes_ctl.bed
    - data/control/GAL4_vs_neg.bed
    - data/chip/cov/norm
    - src/01_extraction.py
    outs:
    - outputs/loops_extracted.pkl
  embedding:
    cmd: python ./src/00_train_embedding.py
    deps:
    - data/genome/saccer3_sgd_2mu.fa
    - src/00_train_embedding.py
    outs:
    - outputs/embeddings/yeast_bpe_tokenizer.json
    - outputs/embeddings/yeast_w2v_embedding.vec
  feature_eng:
    cmd: python ./src/02_feature_eng.py
    deps:
    - outputs/embeddings/yeast_bpe_tokenizer.json
    - outputs/embeddings/yeast_w2v_embedding.vec
    - outputs/loops_extracted.pkl
    - src/02_feature_eng.py
    outs:
    - outputs/loops_features.pkl
